import { format } from 'date-fns'

export function metricStatus(value, target, inverse = false) {
  if (!target || !value) return 'info'
  const ratio = inverse ? target / value : value / target
  if (ratio >= 0.9) return 'green'
  if (ratio >= 0.6) return 'amber'
  return 'red'
}

export function formatReport({ title, summary, metrics = [], insights = [], recommendations = [] }) {
  return {
    title,
    period: format(new Date(), 'MMM d, yyyy'),
    summary,
    metrics,
    insights,
    recommendations,
  }
}

export function toMarkdown(report) {
  const lines = [
    `# ${report.title}`,
    `*${report.period}*\n`,
    `## Executive Summary\n${report.summary}\n`,
  ]
  if (report.metrics.length) {
    lines.push('## Key Metrics')
    report.metrics.forEach(m => {
      const vs = m.target != null ? ` (target: ${m.prefix ?? ''}${m.target}${m.unit ?? ''})` : ''
      lines.push(`- **${m.label}:** ${m.prefix ?? ''}${m.value}${m.unit ?? ''}${vs} — ${m.status.toUpperCase()}`)
    })
    lines.push('')
  }
  if (report.insights.length) {
    lines.push('## Insights')
    report.insights.forEach(i => lines.push(`- [${i.severity.toUpperCase()}] ${i.text}`))
    lines.push('')
  }
  if (report.recommendations.length) {
    lines.push('## Recommendations')
    report.recommendations.forEach((r, idx) => lines.push(`${idx + 1}. ${r}`))
  }
  lines.push(`\n---\n*Generated by ConvoFlow Dashboard · ${report.period}*`)
  return lines.join('\n')
}
